
default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  timeout: 5000

development:
  <<: *default
  username: sb
  password: swahilibox
  database: sb


test:
  <<: *default
  username: sb
  password: swahilibox
  database: sb

production:
  <<: *default
  username: sb
  password: swahilibox
  database: sb
